/**
 * Shared TypeScript types for LevlCast.
 *
 * Import from here instead of defining local interfaces in each file.
 * Keeps the type contract consistent across the codebase.
 *
 * Example:
 *   import type { Peak, CoachReport, VodStatus } from "@/types";
 */

// ─── VOD ─────────────────────────────────────────────────────────────────────

/**
 * Status lifecycle of a VOD analysis job.
 *
 *   pending → transcribing → analyzing → ready
 *                         ↘ failed (at any step)
 */
export type VodStatus =
  | "pending"
  | "transcribing"
  | "analyzing"
  | "ready"
  | "failed";

/** A VOD row as stored in the `vods` Supabase table. */
export interface Vod {
  id: string;
  user_id: string;
  twitch_vod_id: string;
  title: string;
  duration_seconds: number;
  thumbnail_url: string | null;
  view_count: number;
  status: VodStatus;
  analyzed_at: string | null;
  peak_data: Peak[] | null;
  coach_report: CoachReport | null;
  share_token: string | null;
  created_at: string;
  updated_at: string;
}

// ─── PEAKS ───────────────────────────────────────────────────────────────────

/** Categories Claude uses to classify a peak moment. */
export type PeakCategory = "hype" | "funny" | "emotional" | "educational";

/**
 * A peak moment detected by Claude in a VOD transcript.
 * Stored as a JSON array in the `peak_data` column on the `vods` table.
 */
export interface Peak {
  /** Short clip title (< 60 chars), written as a hook/reaction. */
  title: string;
  /** Start time in seconds from the beginning of the VOD. */
  start: number;
  /** End time in seconds from the beginning of the VOD. */
  end: number;
  /** Virality score from 0.0 to 1.0. Only peaks >= 0.5 are kept. */
  score: number;
  /** Broad category of the moment. */
  category: PeakCategory;
  /** Why this moment will perform — Claude's specific reasoning. */
  reason: string;
  /** TikTok-style caption (< 150 chars) with hashtags. */
  caption: string;
  /** Description of the clip's opening 3 seconds (scroll-stopping hook). */
  hook: string;
}

// ─── COACH REPORT ────────────────────────────────────────────────────────────

/** Overall energy arc of the stream. */
export type EnergyTrend = "building" | "declining" | "consistent" | "volatile";

/** How likely viewers were to drop off mid-stream. */
export type RetentionRisk = "low" | "medium" | "high";

/**
 * AI coaching report generated by Claude after peak detection.
 * Stored as JSON in the `coach_report` column on the `vods` table.
 */
export interface CoachReport {
  /** Stream performance score from 0–100. Most streams land between 50–75. */
  overall_score: number;
  /** How the streamer's energy changed throughout the stream. */
  energy_trend: EnergyTrend;
  /** Specific strengths with examples from the actual stream. */
  strengths: string[];
  /** Specific problems + what to do differently, with concrete examples. */
  improvements: string[];
  /** The single best moment from the stream. */
  best_moment: {
    /** Timestamp in MM:SS format. */
    time: string;
    /** What happened, why it worked, and what it reveals about the streamer. */
    description: string;
  };
  /** The single highest-leverage thing to do differently next stream. */
  recommendation: string;
  /** Legacy: present on historical reports only — no longer generated. */
  next_stream_goals?: string[];
  /** How likely the stream was to lose viewers mid-way. */
  viewer_retention_risk: RetentionRisk;
  /** How strong the stream's opening was (first 5 minutes). */
  cold_open?: { score: "strong" | "average" | "weak"; note: string };
  /** Longest silence/low-energy gaps detected in the stream. */
  dead_zones?: Array<{ time: string; duration: number }>;
  /** Two specific minutes to rewatch — one model-behavior moment, one teachable mistake. */
  rewatch_moments?: Array<{ time: string; kind: "best" | "worst"; note: string }>;
  /** The moment that should've been THE clip but wasn't fully realized. */
  missed_clip?: { time: string; note: string };
}

// ─── CLIPS ───────────────────────────────────────────────────────────────────

/** Status of a generated clip. */
export type ClipStatus = "processing" | "ready" | "failed";

/** A clip row as stored in the `clips` Supabase table. */
export interface Clip {
  id: string;
  user_id: string;
  vod_id: string;
  /** Which peak this clip was generated from (index into `peak_data`). */
  peak_index: number;
  title: string;
  caption: string;
  /** Public URL to the clip file in Supabase Storage. */
  storage_url: string | null;
  status: ClipStatus;
  /** Duration of the clip in seconds. */
  duration_seconds: number | null;
  created_at: string;
}

// ─── PROFILES ────────────────────────────────────────────────────────────────

/** Subscription plan tier. */
export type Plan = "free" | "pro";

/** A user profile row from the `profiles` Supabase table. */
export interface Profile {
  id: string;
  twitch_login: string;
  twitch_display_name: string;
  twitch_avatar_url: string | null;
  plan: Plan;
  subscription_expires_at: string | null;
  created_at: string;
  updated_at: string;
}

// ─── USAGE ───────────────────────────────────────────────────────────────────

/**
 * Current usage stats for a user, returned by `getUserUsage()`.
 * Used throughout the dashboard and API routes to enforce plan limits.
 */
export interface UserUsage {
  plan: Plan;
  /** Number of VOD analyses run (or in progress) this calendar month. */
  analyses_this_month: number;
  /** Total clips successfully generated (all time). */
  clips_total: number;
  /** Whether the user can start another analysis right now. */
  can_analyze: boolean;
  /** Whether the user can generate another clip right now. */
  can_generate_clip: boolean;
}
